apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  namespaceSelector:
    matchNames:
      - test
  selector:
    matchLabels:
      app: example-app
  endpoints:
    - targetPort: 8080
