version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - xpack.license.self_generated.type=trial
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.24
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=password
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic: