apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: server
  namespace: argocd
spec:
  description: Project for server

  sourceRepos:
  - '*'

  destinations:
  - namespace: server
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  orphanedResources:
    warn: false
