version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - xpack.license.self_generated.type=trial
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
    ports:
      - 9200:9200

