services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
